default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pinboard_development

test:
  <<: *default
  database: pinboard_test

production:
  <<: *default
  database: pinboard_production
  username: pinboard
  password: <%= ENV['PINBOARD_DATABASE_PASSWORD'] %>
